.TH PEOPLE-CLI "1" "June 2016" "people-cli 0.12"
.SH NAME
people-cli \- a remote procedure call client for People Core. 
.SH SYNOPSIS
people-cli [options] <command> [params] \- Send command to People Core. 
.TP
people-cli [options] help \- Asks People Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the people-cli program. people-cli is an RPC client used to send commands to People Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBpeopled\fP, \fBpeople.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
